### ISSUE TITLE
Humble Chameleon intial install error

### ISSUE THREAD

**Issue by braaqwesi** [fkasler/flik#1]
TASK [Create tools directory] **************************************************
fatal: [domain.app]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@domain.app: Permission denied (publickey).", "unreachable": true}
to retry, use: --limit @/home/trubox/SE/flik/playbooks/humble_setup.retry PLAY RECAP *********************************************************************
logouts.app : ok=0 changed=0 unreachable=1 failed=0

DOmain name is from gandi

VPS is from Gcloud

I sense installtion is initiating SSH connection to the server but getting auth failure due to permission denied on Public key.
]]What do i do to fix this

**Comment by fkasler** [comment]
You probably need to chmod your ssh key so that ansible can use it to auth to your server.
